name: Cycle Website CI/CD

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:

  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check website files
        run: |
          test -f index.html
          test -f Dockerfile

      - name: Build Docker image for testing
        run: docker build -t cycle-website:test .


  build:
    name: Build Docker Image
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cycle-website:latest .
  push-image:
    name: Push Docker Image
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/santhosh2331/cycle-website:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/santhosh2331/cycle-website:latest
  